### ISSUE TITLE
Create fake detector+classifier

### ISSUE THREAD

**Issue by yhoazk** [Kairos-Automotive/carla-brain#17]
Implement the first part of this node. This consists of publish if there is  an incoming traffic light. This will trigger the classifier to estimate if the car shall stop.

**Comment by asimonov** [comment]
I think simulator or provided code publishes positions and states of traffic lights. Or their positions are in a file. So we can implement fake detector by just publishing those.

Then when we have real detector it will replace fake

_____________________________
Kind Regards,
Alexey Simonov

**Comment by yhoazk** [comment]
What I have in mind is to implement the part which notifies the classifier to 
start the classification. The classificaion, I think, is only done if a traffic light 
is in the published `final_waypoints`(close to the car), otherwise it shall not classify. 

Also, I think we can use a fake/random red traffic light detected so others can 
start to complete the full waypoint_updater.

**Comment by dabavil** [comment]
Yes, the simulator publishes the real status of traffic lights to topic `/vehicle/traffic_lights` so using that would be a nice shortcut for now.
