### ISSUE TITLE
Develop Waypoint Updater ( Full )

### ISSUE THREAD

**Issue by yhoazk** [Kairos-Automotive/carla-brain#27]
Complete the waypoint updater functionality.
It needs to change the velocity of the published `/final_waypoints`  accordingly to the incoming traffic light state.

**Comment by yhoazk** [comment]
Need to agree on the best input for the controller, a step or a ramp.

**Comment by asimonov** [comment]
hm, I think we can try step-change and hope the controller will smooth out the transition.
but this is just an opinion.
think you need to experiment and see what is better

**Comment by asimonov** [comment]
Gustavo, after my dl_detector changes you can work on the updater. It can now run on modest hardware. And it obeys the traffic lights. 

Looks like the car starts quite rapidly -- probably needs ramping up. Not sure about the deceleration.

**Comment by yhoazk** [comment]
I'll add a ramp for the positive acceleration also. 👍

**Comment by asimonov** [comment]
Gustavo, I see you define current_tfl_state inside updater. This is not needed. The 'traffic_waypoint' published is different from -1 only if it is RED traffic light. So just rely on this fact.

Also, please do not subscribe to /vehicle/traffic_lights. It is just debug info and we use it in 'fake' tl detector. Updater should only watch /traffic_waypoint and base its logic on that

**Comment by yhoazk** [comment]
Yep, I'll remove them. This changes were before the modification in the tl_classifier which gives this information, and  were used to test the ramp-up/down. 👍

**Comment by asimonov** [comment]
@yhoazk Gustavo, do you work on anything else here in the updater? If not we can close the issue.

**Comment by yhoazk** [comment]
I think we can close it, my attempts were not much better than the current implementation. But they were complicated, and needed some more libraries. I believe a redesign in the controller with a more permisive error policy will improve the whole behaviour. But for the moment is out of scope.

**Comment by asimonov** [comment]
Gustavo,

Thank you for trying!
Let’s leave it.

Kind Regards,
Alexey
