### ISSUE TITLE
Implement detection of closest traffic light ahead of the vehicle

### ISSUE THREAD

**Issue by dabavil** [Kairos-Automotive/carla-brain#29]

**Comment by yhoazk** [comment]
Hi, 
Could you describe this issue? 
Currently the closest traffic light is detected here [https://github.com/Kairos-Automotive/carla-brain/blob/master/ros/src/tl_detector/tl_detector.py#L190-L198](https://github.com/Kairos-Automotive/carla-brain/blob/master/ros/src/tl_detector/tl_detector.py#L190-L198)

And published in `/traffic_waypoint`  with the index of the waypoint or -1 if the traffic light is not in range.

**Comment by dabavil** [comment]
Oops, sorry Gustavo, I didn't realize you had already implemented this as part of the fake detector & classifier. Going to close this now.
