### ISSUE TITLE
Modify the tl_detector so it detects only if a traffic light is in range to be detected.

### ISSUE THREAD

**Issue by yhoazk** [Kairos-Automotive/carla-brain#52]
The module tl_detector contains a variable `self.in_range` which is true when a traffic light is close and it will appear in the camera. If the variable is false no detection nor classification shall be performed.

**Comment by asimonov** [comment]
Looking at the code I see we set light=True at the same time as in_range=True. and later on call detection only if light==True. so in effect it is already working as you described -- the tensorflow code only runs when we are close to traffic lights position

**Comment by yhoazk** [comment]
Yes, that's correct. We can close this issue.
