### ISSUE TITLE
current_velocity must be published before process_waypoint (line 219) is called.

### ISSUE THREAD

**Issue by avrabe** [Kairos-Automotive/carla-brain#67]
https://github.com/Kairos-Automotive/carla-brain/blob/f2ac33e06f9e2a622157bcc31d29a5ebefeacb91/ros/src/waypoint_updater/waypoint_updater.py#L215

Otherwise 
  File "/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 215, in publish_waypoints_ahead
    self.current_velocity = self.current_velocity+0.5 if self.current_velocity < MAX_SPEED else self.current_velocity
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by asimonov** [comment]
@yhoazk Gustavo, is this still outstanding? If not can you close?

**Comment by yhoazk** [comment]
Closed by Waypoint improvements  #76
