### ISSUE TITLE
did we change only ros/src?

### ISSUE THREAD

**Issue by asimonov** [Kairos-Automotive/carla-brain#98]
https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/455f33f0-2c2d-489d-9ab2-201698fbf21a

says:

*The code that you will need to modify for the project will be contained entirely within the (path_to_project_repo)/ros/src/ directory*

need to check if we modified anything outside this.
some people on slack ask questions related to changes in launch files not picked up...

**Comment by asimonov** [comment]
and on project submission it says:

Launch correctly using the launch files provided in the capstone repo. Please note that we will not be able to accomodate special launch instructions or run additional scripts from your submission to download files. The launch/styx.launch and launch/site.launch files will be used to test code in the simulator and on the vehicle respectively. The submission size limit for this project has been increased to 2GB.

**Comment by asimonov** [comment]
I see that we updated both launch files under ros/launch.
not sure if this change will be picked up for carla (and for simulator review...)

looking at John Chen's team final repo I see they created a few other files but did not touch the original ones:
https://github.com/diyjac/SDC-System-Integration/tree/master/ros/launch

**Comment by yhoazk** [comment]
The changes we have made are:
`/ros/launch/site.launch`
```
+    <param name="lookahead_wps" type="int" value="20"/>
+    <param name="current_env" value="live" />
```
And for `/ros/launch/styx.launch`
```
+    <arg name="monkey_patch" default="false" />
+    <param name="do_monkey_patch" type="bool" value="$(arg monkey_patch)"/>
+    <param name="lookahead_wps" type="int" value="200"/>
+    <!--Set environment variable -->
+    <param name="current_env" value="simulator" />
+
```

I think we can add other configuration files or hardcode them inside of a try/catch.

**Comment by yhoazk** [comment]
Looking more in detail, the added parameters have a fallback case. Then it works even if we remove the changes. Or at least the part which normally works in my lap-top.
